### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 3000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 3000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "672107cba8424128947909202c9d6dbc",
  "accountNumber": "1000000000",
  "amount": 3000
}

### query transaction
GET http://localhost:8080/transaction/8a6e8a1b7f8c44e2aaf929b85b037536